/*This terraform file has been generated programmatically using terraform-generator.*/
/*All the commented lines, if any, are optional. Remove comment characters, if required, before using.*/
/*Refer https://github.com/sushil46in/terraform_modules.git for more details.*/

output "network_load_balancer_network_load_balancers_backend_sets_unified_id" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.id
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_ip_version" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.ip_version
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_is_preserve_source" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.is_preserve_source
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_name" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.name
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_network_load_balancer_id" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.network_load_balancer_id
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_policy" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.policy
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends_ip_address" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.ip_address
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends_is_backup" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.is_backup
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends_is_drain" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.is_drain
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends_is_offline" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.is_offline
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends_name" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.name
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends_target_id" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.target_id
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends_weight" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.weight
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_backends" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.backends
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_interval_in_millis" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.interval_in_millis
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_port" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.port
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_request_data" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.request_data
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_response_body_regex" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.response_body_regex
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_response_data" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.response_data
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_retries" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.retries
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_return_code" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.return_code
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_timeout_in_millis" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.timeout_in_millis
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker_url_path" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.url_path
}

output "network_load_balancer_network_load_balancers_backend_sets_unified_health_checker" {
  value = oci_network_load_balancer_network_load_balancers_backend_sets_unified.resname.health_checker
}

