/*This terraform file has been generated programmatically using terraform-generator.*/
/*All the commented lines, if any, are optional. Remove comment characters, if required, before using.*/
/*Refer https://github.com/sushil46in/terraform_modules.git for more details.*/

output "database_autonomous_container_database_dataguard_association_apply_lag" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.apply_lag
}

output "database_autonomous_container_database_dataguard_association_apply_rate" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.apply_rate
}

output "database_autonomous_container_database_dataguard_association_autonomous_container_database_dataguard_association_id" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.autonomous_container_database_dataguard_association_id
}

output "database_autonomous_container_database_dataguard_association_autonomous_container_database_id" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.autonomous_container_database_id
}

output "database_autonomous_container_database_dataguard_association_id" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.id
}

output "database_autonomous_container_database_dataguard_association_is_automatic_failover_enabled" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.is_automatic_failover_enabled
}

output "database_autonomous_container_database_dataguard_association_lifecycle_details" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.lifecycle_details
}

output "database_autonomous_container_database_dataguard_association_peer_autonomous_container_database_dataguard_association_id" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.peer_autonomous_container_database_dataguard_association_id
}

output "database_autonomous_container_database_dataguard_association_peer_autonomous_container_database_id" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.peer_autonomous_container_database_id
}

output "database_autonomous_container_database_dataguard_association_peer_lifecycle_state" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.peer_lifecycle_state
}

output "database_autonomous_container_database_dataguard_association_peer_role" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.peer_role
}

output "database_autonomous_container_database_dataguard_association_protection_mode" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.protection_mode
}

output "database_autonomous_container_database_dataguard_association_role" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.role
}

output "database_autonomous_container_database_dataguard_association_state" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.state
}

output "database_autonomous_container_database_dataguard_association_time_created" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.time_created
}

output "database_autonomous_container_database_dataguard_association_time_last_role_changed" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.time_last_role_changed
}

output "database_autonomous_container_database_dataguard_association_time_last_synced" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.time_last_synced
}

output "database_autonomous_container_database_dataguard_association_transport_lag" {
  value = oci_database_autonomous_container_database_dataguard_association.resname.transport_lag
}

