/*This terraform file has been generated programmatically using terraform-generator.*/
/*All the commented lines, if any, are optional. Remove comment characters, if required, before using.*/
/*Refer https://github.com/sushil46in/terraform_modules.git for more details.*/

/*variable "vertex_ai_featurestore_entitytype_description" {
  description = "(Optional)" #Optional. Description of the EntityType.
  type = string
}*/

variable "vertex_ai_featurestore_entitytype_featurestore" {
  description = "(Required)" #The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}.
  type = string
}

/*variable "vertex_ai_featurestore_entitytype_labels" {
  description = "(Optional)" #A set of key/value label pairs to assign to this EntityType.
  type = map
}*/

/*variable "vertex_ai_featurestore_entitytype_name" {
  description = "(Optional)" #The name of the EntityType. This value may be up to 60 characters, and valid characters are [a-z0-9_]. The first character cannot be a number.
  type = string
}*/

variable "vertex_ai_featurestore_entitytype_categorical_threshold_config_value" {
  description = "(Required)" #Specify a threshold value that can trigger the alert. For categorical feature, the distribution distance is calculated by L-inifinity norm. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3.
  type = number
}

/*variable "vertex_ai_featurestore_entitytype_import_features_analysis_anomaly_detection_baseline" {
  description = "(Optional)" #Defines the baseline to do anomaly detection for feature values imported by each [entityTypes.importFeatureValues][] operation. The value must be one of the values below:  LATEST_STATS: Choose the later one statistics generated by either most recent snapshot analysis or previous import features analysis. If non of them exists, skip anomaly detection and only generate a statistics.  MOST_RECENT_SNAPSHOT_STATS: Use the statistics generated by the most recent snapshot analysis if exists.  PREVIOUS_IMPORT_FEATURES_STATS: Use the statistics generated by the previous import features analysis if exists.
  type = string
}*/

/*variable "vertex_ai_featurestore_entitytype_import_features_analysis_state" {
  description = "(Optional)" #Whether to enable / disable / inherite default hebavior for import features analysis. The value must be one of the values below:  DEFAULT: The default behavior of whether to enable the monitoring. EntityType-level config: disabled.  ENABLED: Explicitly enables import features analysis. EntityType-level config: by default enables import features analysis for all Features under it.  DISABLED: Explicitly disables import features analysis. EntityType-level config: by default disables import features analysis for all Features under it.
  type = string
}*/

variable "vertex_ai_featurestore_entitytype_numerical_threshold_config_value" {
  description = "(Required)" #Specify a threshold value that can trigger the alert. For numerical feature, the distribution distance is calculated by Jensen–Shannon divergence. Each feature must have a non-zero threshold if they need to be monitored. Otherwise no alert will be triggered for that feature. The default value is 0.3.
  type = number
}

/*variable "vertex_ai_featurestore_entitytype_snapshot_analysis_disabled" {
  description = "(Optional)" #The monitoring schedule for snapshot analysis. For EntityType-level config: unset / disabled = true indicates disabled by default for Features under it; otherwise by default enable snapshot analysis monitoring with monitoringInterval for Features under it.
  type = bool
}*/

/*variable "vertex_ai_featurestore_entitytype_snapshot_analysis_monitoring_interval_days" {
  description = "(Optional)" #Configuration of the snapshot analysis based monitoring pipeline running interval. The value indicates number of days. The default value is 1. If both FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days and [FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval][] are set when creating/updating EntityTypes/Features, FeaturestoreMonitoringConfig.SnapshotAnalysis.monitoring_interval_days will be used.
  type = number
}*/

/*variable "vertex_ai_featurestore_entitytype_snapshot_analysis_staleness_days" {
  description = "(Optional)" #Customized export features time window for snapshot analysis. Unit is one day. The default value is 21 days. Minimum value is 1 day. Maximum value is 4000 days.
  type = number
}*/

/*variable "vertex_ai_featurestore_entitytype_timeouts_create" {
  description = "(Optional)" #The value for timeouts_create
  type = string
}*/

/*variable "vertex_ai_featurestore_entitytype_timeouts_delete" {
  description = "(Optional)" #The value for timeouts_delete
  type = string
}*/

/*variable "vertex_ai_featurestore_entitytype_timeouts_update" {
  description = "(Optional)" #The value for timeouts_update
  type = string
}*/

